name: petstore_client_lib_fake_tests
version: 1.0.0
description: OpenAPI API Dart DIO client tests for petstore_client_lib_fake

publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  built_collection: 5.1.0
  built_value: 8.1.0
  dio: 4.0.0
  http_mock_adapter: 0.3.2
  mockito: 5.0.11
  openapi:
    path: ../petstore_client_lib_fake
  test: 1.17.4
