name: petstore_client
version: 1.0.0
description: Petstore client using OpenAPI library

publish_to: none

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  openapi:
    path: ../petstore_client_lib

dev_dependencies:
  meta: <1.7.0
  test: ^1.8.0
  mockito: ^4.1.1
  http: ^0.13.0
  collection: ^1.14.12
