[package]
name = "swagger"
version = "1.0.0"
authors = ["Swagger Codegen team and contributors"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_yaml = "*"
serde_json = "*"
base64 = "*"
futures = "*"
hyper = "*"
url = "*"

[dev-dependencies]
tokio-core = "*"
