name: openapi
version: 1.0.0
description: OpenAPI API client
environment:
    sdk: ">=2.0.0 <3.0.0"
dependencies:
    jaguar_retrofit: '^2.4.1'
    jaguar_serializer: '^2.2.0'
dev_dependencies:
    jaguar_retrofit_gen: '^2.4.2'
    jaguar_serializer_cli: '^2.2.1'
    build_runner: '^0.10.0'