generatorName: clojure
outputDir: samples/client/petstore/clojure
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.json
templateDir: modules/openapi-generator/src/main/resources/clojure
