generatorName: android
outputDir: samples/client/petstore/android/volley
library: volley
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/android
additionalProperties:
  artifactId: petstore-android-volley
