generatorName: cpp-httplib-server
outputDir: samples/server/petstore/cpp-httplib-server/petstore
inputSpec: modules/openapi-generator/src/test/resources/3_0/cpp-httplib-server/petstore.json
templateDir: modules/openapi-generator/src/main/resources/cpp-httplib-server
additionalProperties:
  apiNamespace: "api"
  modelNamespace: "models"
  projectName: "cpp-httplib-server-petstore"
