# for .net standard
generatorName: csharp
outputDir: samples/client/petstore/csharp/restsharp/net7/OpenAPIClient-net5.0
inputSpec: modules/openapi-generator/src/test/resources/3_0/csharp/petstore-with-fake-endpoints-models-for-testing-with-http-signature-oneof-primitive-types.yaml
templateDir: modules/openapi-generator/src/main/resources/csharp
additionalProperties:
  packageGuid: '{321C8C3F-0156-40C1-AE42-D59761FB9B6C}'
  useCompareNetObjects: true 
  disallowAdditionalPropertiesIfNotPresent: false
  useOneOfDiscriminatorLookup: true
  targetFramework: net7.0
  equatable: true
enumNameMappings:
  delivered: Shipped
