# for csharp generichost
generatorName: csharp
outputDir: samples/client/petstore/csharp/generichost/standard2.0/Petstore
inputSpec: modules/openapi-generator/src/test/resources/3_0/csharp/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
templateDir: modules/openapi-generator/src/main/resources/csharp
additionalProperties:
  packageGuid: '{321C8C3F-0156-40C1-AE42-D59761FB9B6C}'
  useCompareNetObjects: true 
  disallowAdditionalPropertiesIfNotPresent: false
  targetFramework: netstandard2.0
  equatable: true
  modelPropertySorting: alphabetical
  operationParameterSorting: alphabetical
