# for csharp generichost
generatorName: csharp
outputDir: samples/client/petstore/csharp/generichost/latest/ComposedEnum
inputSpec: modules/openapi-generator/src/test/resources/3_0/csharp/composed-enum.yaml
templateDir: modules/openapi-generator/src/main/resources/csharp
additionalProperties:
  packageGuid: '{321C8C3F-0156-40C1-AE42-D59761FB9B6C}'
  modelPropertySorting: alphabetical
  operationParameterSorting: alphabetical
validateSpec: false
