generatorName: go
outputDir: samples/openapi3/client/petstore/go-petstore-withXml
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-addpet-only.yaml
templateDir: modules/openapi-generator/src/main/resources/go
additionalProperties:
  enumClassPrefix: "true"
  packageName: petstore
  disallowAdditionalPropertiesIfNotPresent: false
  withXml: true
