generatorName: groovy
outputDir: samples/client/petstore/groovy
inputSpec: modules/openapi-generator/src/test/resources/3_0/groovy/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/Groovy
additionalProperties:
  enumPropertyNaming: "original"
  hideGenerationTimestamp: "true"
