generatorName: java-micronaut-client
outputDir: samples/client/petstore/java-micronaut-client/
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
additionalProperties:
  artifactId: petstore-micronaut
  hideGenerationTimestamp: "true"
  configureAuth: "false"
  build: "all"
  test: "spock"
  requiredPropertiesInConstructor: "false"
