generatorName: java
outputDir: samples/client/petstore/java/webclient
library: webclient
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-webclient
  hideGenerationTimestamp: "true"
