generatorName: java
outputDir: samples/client/petstore/java/jersey2-java8
library: jersey2
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-jersey2-java8
  hideGenerationTimestamp: true
  serverPort: "8082"
  dateLibrary: java8
  useOneOfDiscriminatorLookup: true
