generatorName: java
outputDir: samples/client/petstore/java/native-useGzipFeature
library: native
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-addpet-only.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-native-useGzipFeature
  hideGenerationTimestamp: "true"
  useJakartaEe: "true"
