generatorName: java-helidon-client
library: mp
outputDir: samples/client/petstore/java-helidon-client/v4/mp
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/java-helidon/client
additionalProperties:
  helidonVersion: 4.0.11
  artifactId: petstore-helidon-client-mp
  hideGenerationTimestamp: "true"
  configureAuth: "false"
  build: "all"
  test: "spock"
  requiredPropertiesInConstructor: "false"
  visitable: "true"
  fullProject: "true"
