generatorName: java
outputDir: samples/client/others/java/webclient-sealedInterface_3_1
library: webclient
inputSpec: modules/openapi-generator/src/test/resources/3_1/oneof_polymorphism_and_inheritance.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: sealed-interface-webclient
  hideGenerationTimestamp: "true"
  useOneOfInterfaces: true
  useSealedOneOfInterfaces: true
