generatorName: java
outputDir: samples/client/petstore/java/retrofit2-play26
library: retrofit2
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  usePlayWS: "true"
  enableBuilderSupport: "true"
  useBeanValidation: "true"
  playVersion: play26
  artifactId: petstore-java-client-retrofit2-play26
  hideGenerationTimestamp: "true"
