generatorName: java-helidon-server
library: mp
outputDir: samples/server/petstore/java-helidon-server/v4/mp
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/java-helidon/server
additionalProperties:
  helidonVersion: 4.0.11
  artifactId: petstore-helidon-server-mp
  hideGenerationTimestamp: "true"
  build: "all"
  test: "spock"
  useAuth: "false"
  fullProject: "true"