generatorName: java-camel
outputDir: samples/server/petstore/java-camel
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/java-camel-server
additionalProperties:
  oas3: "true"
  hideGenerationTimestamp: true
  camelRestBindingMode: "auto"
  performBeanValidation: true
  #dateLibrary: "java8-localdatetime"
  camelDataformatProperties: "json.out.disableFeatures=WRITE_DATES_AS_TIMESTAMPS"
  library: "spring-boot"
  withXml: true
  jackson: true
  camelUseDefaultValidationtErrorProcessor: true
  camelRestClientRequestValidation: true
  camelSecurityDefinitions: true
