generatorName: java
outputDir: samples/client/petstore/java/resteasy-echo
inputSpec: modules/openapi-generator/src/test/resources/3_0/echo_api.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-resteasy-echo
  hideGenerationTimestamp: "true"
  library: resteasy
