generatorName: java-helidon-client
library: se
outputDir: samples/client/petstore/java-helidon-client/v3/se
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/java-helidon/client
additionalProperties:
  helidonVersion: 3.2.7
  artifactId: petstore-helidon-client-se
  hideGenerationTimestamp: "true"
  configureAuth: "false"
  build: "all"
  test: "spock"
  requiredPropertiesInConstructor: "false"
  visitable: "true"
  fullProject: "true"
