generatorName: jaxrs-cxf
outputDir: samples/server/petstore/jaxrs-cxf
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaJaxRS/cxf
additionalProperties:
  hideGenerationTimestamp: "true"
  serverPort: "8082"
  implicitHeadersRegex: (api_key|enum_header_string)
