generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-spring
additionalProperties:
  serviceImplementation: "true"
  serializableModel: "true"
  swaggerAnnotations: "true"
  beanValidations: "true"
