generatorName: kotlin
outputDir: samples/client/petstore/kotlin-jvm-ktor-kotlinx_serialization
library: jvm-ktor
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-jvm-ktor-kotlinx_serialization
  serializationLibrary: kotlinx_serialization
