generatorName: kotlin
outputDir: samples/client/petstore/kotlin-nonpublic
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-dollars.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  nonPublicApi: "true"
  artifactId: kotlin-petstore-nonpublic
