generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot-include-http-request-context-delegate
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/3_0/kotlin/petstore-with-x-kotlin-implements.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: none
  annotationLibrary: swagger1
  useSwaggerUI: false
  serviceImplementation: false
  skipDefaultInterface: true
  interfaceOnly: false
  serializableModel: true
  beanValidations: true
  includeHttpRequestContext: true
  reactive: true
  delegatePattern: true
