generatorName: kotlin
outputDir: samples/client/petstore/kotlin-jvm-spring-webclient
library: jvm-spring-webclient
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-petstore-spring-webclient
  enumUnknownDefaultCase: true
  serializationLibrary: jackson
