generatorName: kotlin-server
outputDir: samples/server/petstore/kotlin-server/jaxrs-spec
library: jaxrs-spec
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-dollars.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-server
additionalProperties:
  useCoroutines: "true"
