generatorName: kotlin
outputDir: samples/client/others/kotlin-oneOf-discriminator-kotlinx-serialization
inputSpec: modules/openapi-generator/src/test/resources/3_0/kotlin/polymorphism-oneof-discriminator.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-oneOf-discriminator
  serializableModel: "false"
  dateLibrary: java8
  library: jvm-retrofit2
  enumUnknownDefaultCase: true
  serializationLibrary: kotlinx_serialization
  generateOneOfAnyOfWrappers: true
