generatorName: ocaml
outputDir: samples/client/petstore/ocaml-oneOf-primitive
inputSpec: modules/openapi-generator/src/test/resources/3_0/oneOf_primitive.yaml
templateDir: modules/openapi-generator/src/main/resources/ocaml
additionalProperties:
  packageName: petstore_client
