generatorName: python
outputDir: samples/client/echo_api/python-disallowAdditionalPropertiesIfNotPresent
inputSpec: modules/openapi-generator/src/test/resources/3_0/echo_api.yaml
templateDir: modules/openapi-generator/src/main/resources/python
additionalProperties:
  hideGenerationTimestamp: "true"
  disallowAdditionalPropertiesIfNotPresent: "true"
  setEnsureAsciiToFalse: true
