generatorName: python
outputDir: samples/openapi3/client/petstore/python-httpx
inputSpec: modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/python
library: httpx
additionalProperties:
  packageName: petstore_api
  mapNumberTo: float
  poetry1: true
nameMappings:
  _type: underscore_type
  type_: type_with_underscore
modelNameMappings:
  # The OpenAPI spec ApiResponse conflicts with the internal ApiResponse
  ApiResponse: ModelApiResponse
