generatorName: rust
outputDir: samples/client/others/rust/hyper/discriminator-reserved-keyword
library: hyper
inputSpec: modules/openapi-generator/src/test/resources/3_0/rust/discriminator-reserved-keyword.yaml
templateDir: modules/openapi-generator/src/main/resources/rust
additionalProperties:
  supportAsync: false
  packageName: discriminator-reserved-keyword-hyper
