generatorName: rust-server
outputDir: samples/server/petstore/rust-server/output/petstore-with-fake-endpoints-models-for-testing
inputSpec: modules/openapi-generator/src/test/resources/2_0/rust-server/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/rust-server
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: petstore-with-fake-endpoints-models-for-testing
  publishRustRegistry: crates-io
