generatorName: scala-sttp4
outputDir: samples/client/petstore/scala-sttp4
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/scala-sttp4
additionalProperties:
  hideGenerationTimestamp: "true"
