generatorName: spring
outputDir: samples/openapi3/client/petstore/spring-cloud-spring-pageable
library: spring-cloud
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-spring-pageable.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapitools.openapi3
  oas3: "true"
  artifactId: spring-cloud-spring-pageable
  hideGenerationTimestamp: 'true'
