generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-nullable.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapitools.openapi3
  documentationProvider: springdoc
  useOptional: true
  artifactId: springboot
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
