generatorName: spring
library: spring-cloud
outputDir: samples/openapi3/client/petstore/spring-cloud-4-with-optional
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapitools.openapi3
  documentationProvider: springdoc
  artifactId: spring-cloud-oas4
  useSpringBoot4: "true"
  useJackson3: true
  openApiNullable: false
  dateLibrary: "java8"
  useOptional: "true"
  useSwaggerUI: "false"
  hideGenerationTimestamp: "true"
  documentationProvider: none
  #optionalAcceptNullable: "false" # default to true
