generatorName: spring
outputDir: samples/server/petstore/springboot-beanvalidation-no-nullable
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  java8: "false"
  useBeanValidation: true
  artifactId: spring-boot-beanvalidation-no-nullable
  hideGenerationTimestamp: "true"
  openApiNullable: "false"
