generatorName: spring
outputDir: samples/openapi3/server/petstore/springboot-jspecify
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  groupId: org.openapitools.openapi.jspecify
  documentationProvider: springdoc
  artifactId: springboot
  snapshotVersion: "true"
  useSpringBoot3: true
  useBeanValidation: true
  hideGenerationTimestamp: "true"
  generateConstructorWithAllArgs: true
  additionalModelTypeAnnotations: '@org.jspecify.annotations.NullMarked'
importMappings:
  Nullable: org.jspecify.annotations.Nullable
