generatorName: spring
library: spring-http-interface
outputDir: samples/client/petstore/spring-http-interface-reactive-bean-validation
inputSpec: modules/openapi-generator/src/test/resources/3_0/spring/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  artifactId: spring-http-interface-reactive
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
  reactive: "true"
  # validation should be respected
  useBeanValidation: "true"
  # documentation provider should be ignored
  documentationProvider: "springfox"
  # annotation provider should be ignored
  annotationLibrary: "swagger1"

