generatorName: spring
library: spring-http-interface
outputDir: samples/client/petstore/spring-http-interface-oauth
inputSpec: modules/openapi-generator/src/test/resources/3_0/spring/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  artifactId: spring-http-interface-oauth
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
  modelNameSuffix: 'Dto'
  generatedConstructorWithRequiredArgs: "false"
  clientRegistrationId: "petstore-oauth"
  parentGroupId: "org.springframework.boot"
  parentArtifactId: "spring-boot-starter-parent"
  parentVersion: "3.5.0"
