generatorName: spring
outputDir: samples/server/petstore/springboot-implicitHeaders
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  artifactId: springboot-implicitHeaders
  documentationProvider: springfox
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: .*
