generatorName: spring
outputDir: samples/openapi3/server/petstore/spring-mvc
library: spring-mvc
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  java8: "false"
  booleanGetterPrefix: get
  artifactId: spring-mvc-server
  hideGenerationTimestamp: "true"
  serverPort: "8002"
