generatorName: spring
outputDir: samples/server/petstore/springboot-skip-x-implements
inputSpec: modules/openapi-generator/src/test/resources/3_0/spring/petstore-with-fake-endpoints-models-for-testing-x-implements.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  artifactId: springboot
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
  camelCaseDollarSign: "true"
  modelNameSuffix: 'Dto'
  xImplementsOverrides:
    com.custompackage.InterfaceToSubstitute: com.custompackage.SubstitutedInterface
    com.custompackage.InterfaceToSkip: skip
  schemaImplements:
    Foo: [ com.custompackage.FooInterface, com.custompackage.FooIntergace ]
    Animal: [ com.custompackage.AnimalInterfaceImplleeements ]
