generatorName: swift6
outputDir: samples/client/petstore/swift6/objcCompatible
inputSpec: modules/openapi-generator/src/test/resources/2_0/swift/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/swift6
generateAliasAsModel: true
additionalProperties:
  responseAs: ObjcBlock
  podAuthors: ""
  identifiableModels: false
  podSummary: PetstoreClient
  objcCompatible: true
  projectName: PetstoreClient
  podHomepage: https://github.com/openapitools/openapi-generator
