generatorName: swift5
outputDir: samples/client/petstore/swift5/urlsessionLibrary
library: urlsession
inputSpec: modules/openapi-generator/src/test/resources/2_0/swift/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/swift5
generateAliasAsModel: true
additionalProperties:
  podAuthors: ""
  podSummary: PetstoreClient
  projectName: PetstoreClient
  podHomepage: https://github.com/openapitools/openapi-generator
  useSPMFileStructure: true
  useClasses: true
  swiftUseApiNamespace: true
