generatorName: swift5
outputDir: samples/client/petstore/swift5/rxswiftLibrary
inputSpec: modules/openapi-generator/src/test/resources/2_0/swift/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/swift5
generateAliasAsModel: true
additionalProperties:
  responseAs: RxSwift
  podAuthors: ""
  podSummary: PetstoreClient
  projectName: PetstoreClient
  podHomepage: https://github.com/openapitools/openapi-generator
  useBacktickEscapes: true
  generateModelAdditionalProperties: false
