generatorName: typescript
outputDir: samples/openapi3/client/petstore/typescript/builds/object_params
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
additionalProperties:
  platform: node
  npmName: ts-petstore-client
  useObjectParameters: true
  projectName: ts-petstore-client
  moduleName: petstore
