generatorName: typescript-angular
outputDir: samples/client/petstore/typescript-angular-v21/builds/default
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-angular
additionalProperties:
  ngVersion: 21.0.0
  npmName: sample-angular-21-0-0
  supportsES6: true
  ngVersion21: true
