generatorName: typescript-fetch
outputDir: samples/client/others/typescript-fetch/additional-properties-in-multipart-issue
inputSpec: modules/openapi-generator/src/test/resources/3_0/typescript-fetch/additional-properties-in-multipart-issue.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-fetch
additionalProperties:
  enumPropertyNaming: "original"
  enumUnknownDefaultCase: true
