generatorName: typescript-rxjs
outputDir: samples/client/petstore/typescript-rxjs/builds/default
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-rxjs
