generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/without-runtime-checks
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-fetch
additionalProperties:
  npmVersion: 1.0.0
  npmName: '@openapitools/typescript-fetch-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  withoutRuntimeChecks: true
  snapshot: false
