generatorName: typescript-rxjs
outputDir: samples/client/petstore/typescript-rxjs/builds/3.0
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-rxjs
