[package]
name = "petstore-reqwest-awsv4signature"
version = "1.0.0"
authors = ["OpenAPI Generator team and contributors"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
reqwest = "~0.9"
aws-sigv4 = "0.3.0"
http = "0.2.5"
secrecy = "0.8.0"

[dev-dependencies]
