generatorName: scala-finch
outputDir: samples/server/petstore/scala-finch
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/scala-finch
