# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
  - "3.14"
  # uncomment the following if needed
  #- "3.14-dev"  # 3.14 development branch
  #- "nightly"  # nightly build
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
# command to run tests
script: pytest --cov=openapi_client
