generatorName: rust-axum
outputDir: samples/server/petstore/rust-axum/output/openapi-v3
inputSpec: modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
templateDir: modules/openapi-generator/src/main/resources/rust-axum
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  allowBlockingValidator: "true"
  packageName: openapi-v3
  homePageUrl: https://github.com/openapitools/openapi-generator
globalProperties:
  skipFormModel: false
enablePostProcessFile: true
