generatorName: rust-axum
outputDir: samples/server/petstore/rust-axum/output/ping-bearer-auth
inputSpec: modules/openapi-generator/src/test/resources/3_0/rust-server/ping-bearer-auth.yaml
templateDir: modules/openapi-generator/src/main/resources/rust-axum
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: ping-bearer-auth
  homePageUrl: https://github.com/openapitools/openapi-generator
globalProperties:
  skipFormModel: false
enablePostProcessFile: true
