generatorName: csharp
outputDir: samples/client/petstore/csharp/OpenAPIClientNet35
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/csharp
additionalProperties:
  targetFramework: v3.5
  packageGuid: '{321C8C3F-0156-40C1-AE42-D59761FB9B6C}'
