generatorName: eiffel
outputDir: samples/client/petstore/eiffel
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/Eiffel
