generatorName: fsharp-functions
outputDir: samples/server/petstore/fsharp-functions
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/fsharp-functions-server
