name: openapi
version: 1.0.0
description: OpenAPI API client
authors:
  - Author <author@homepage>
homepage: homepage
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: '>=0.12.0 <0.13.0'
dev_dependencies:
  test: ^1.3.0
