name: Samples Java Helidon v4

on:
  push:
    paths:
      - samples/client/petstore/java-helidon-client/v4/**
      - samples/server/petstore/java-helidon-server/v4/**
      - samples/server/others/java-helidon-server/v4/**
  pull_request:
    paths:
      - samples/client/petstore/java-helidon-client/v4/**
      - samples/server/petstore/java-helidon-server/v4/**
      - samples/server/others/java-helidon-server/v4/**
jobs:
  build:
    name: Build Java Helidon 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/java-helidon-client/v4/mp
          - samples/client/petstore/java-helidon-client/v4/se
          - samples/server/petstore/java-helidon-server/v4/mp
          - samples/server/petstore/java-helidon-server/v4/se
          - samples/server/petstore/java-helidon-server/v4/se-uac
          - samples/server/others/java-helidon-server/v4/mp-format-test
        version: [21]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: mvn clean package --no-transfer-progress
