name: Samples C# .Net 9 Clients

on:
  push:
    paths:
      - samples/client/petstore/csharp/generichost/latest/**
      - samples/client/petstore/csharp/generichost/net9/**
      - samples/client/petstore/csharp/httpclient/net9/**
      - samples/client/petstore/csharp/restsharp/net9/**
      - samples/client/petstore/csharp/unityWebRequest/net9/**
  pull_request:
    paths:
      - samples/client/petstore/csharp/generichost/latest/**
      - samples/client/petstore/csharp/generichost/net9/**
      - samples/client/petstore/csharp/httpclient/net9/**
      - samples/client/petstore/csharp/restsharp/net9/**
      - samples/client/petstore/csharp/unityWebRequest/net9/**
jobs:
  build:
    name: Build .Net projects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/csharp/generichost/latest/ComposedEnum
          - samples/client/petstore/csharp/generichost/latest/InlineEnumAnyOf
          - samples/client/petstore/csharp/generichost/latest/Tags
          - samples/client/petstore/csharp/generichost/latest/HelloWorld
          - samples/client/petstore/csharp/generichost/latest/OneOfList
          - samples/client/petstore/csharp/generichost/net9/AllOf
          - samples/client/petstore/csharp/generichost/net9/AnyOf
          - samples/client/petstore/csharp/generichost/net9/AnyOfNoCompare
          - samples/client/petstore/csharp/generichost/net9/FormModels
          # - samples/client/petstore/csharp/generichost/net9/ManualPetstoreTests
          # - samples/client/petstore/csharp/generichost/net9/ManualSourceGenerationTests
          - samples/client/petstore/csharp/generichost/net9/NullReferenceTypes
          - samples/client/petstore/csharp/generichost/net9/OneOf
          - samples/client/petstore/csharp/generichost/net9/Petstore
          - samples/client/petstore/csharp/generichost/net9/SourceGeneration
          - samples/client/petstore/csharp/generichost/net9/UseDateTimeForDate
          # restsharp
          - samples/client/petstore/csharp/restsharp/net9/EnumMappings
          # httpclient
          - samples/client/petstore/csharp/httpclient/net9/Petstore
          - samples/client/petstore/csharp/httpclient/net9/Petstore-nonPublicApi
          # unity
          #- samples/client/petstore/csharp/unityWebRequest/net9/Petstore
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.0.101'
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: dotnet build Org.OpenAPITools.sln
      - name: Test
        working-directory: ${{ matrix.sample }}
        run: dotnet test Org.OpenAPITools.sln
