name: Samples Scala/sbt

on:
  push:
    paths:
      - 'samples/client/petstore/scala**'
      - 'samples/server/petstore/scala**'
      - 'samples/client/petstore/java/okhttp-gson/**'
  pull_request:
    paths:
      - 'samples/client/petstore/scala**'
      - 'samples/server/petstore/scala**'
      - 'samples/client/petstore/java/okhttp-gson/**'
jobs:
  build:
    name: Build sbt/Scala client, servers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/client/petstore/java/okhttp-gson
          - samples/client/petstore/scalaz
          - samples/client/petstore/scala-pekko
          - samples/client/petstore/scala-http4s
          #- samples/client/petstore/scala-sttp
          #- samples/client/petstore/scala-sttp-circe
          # servers
          - samples/server/petstore/scala-lagom-server
          - samples/server/petstore/scala-play-server
          - samples/server/petstore/scala-akka-http-server
          - samples/server/petstore/scala-pekko-http-server
          - samples/server/petstore/scalatra
          - samples/server/petstore/scala-http4s-server
          - samples/server/petstore/scala-cask
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.ivy2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/build.sbt') }}
      - name: Build and test
        working-directory: ${{ matrix.sample }}
        run: sbt -v +test
