name: Samples C# .Net Standard Client

on:
  push:
    paths:
      - samples/client/petstore/csharp/generichost/standard2.0/**
      - samples/client/petstore/csharp/httpclient/standard2.0/**
      - samples/client/petstore/csharp/restsharp/standard2.0/**
      - samples/client/petstore/csharp/unityWebRequest/standard2.0/**
  pull_request:
    paths:
      - samples/client/petstore/csharp/generichost/standard2.0/**
      - samples/client/petstore/csharp/httpclient/standard2.0/**
      - samples/client/petstore/csharp/restsharp/standard2.0/**
      - samples/client/petstore/csharp/unityWebRequest/standard2.0/**
jobs:
  build:
    name: Build .Net projects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/csharp/generichost/standard2.0/OpenAPIClient-generichost-netstandard2.0/
          - samples/client/petstore/csharp/httpclient/standard2.0/OpenAPIClient-httpclient/
          - samples/client/petstore/csharp/restsharp/standard2.0/OpenAPIClient/
          - samples/client/petstore/csharp/restsharp/standard2.0/OpenAPIClient-ConditionalSerialization/
          - samples/client/petstore/csharp/unityWebRequest/standard2.0/OpenAPIClient-unityWebRequest/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 3.1.*
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: dotnet build Org.OpenAPITools.sln
      # skip tests as petstore server it not running
      # these tests are run in appveyor instead
      #- name: Test
      #  working-directory: ${{ matrix.sample }}
      #  run: dotnet test Org.OpenAPITools.sln
