name: Samples Scala

on:
  push:
    paths:
      - 'samples/client/petstore/scala**'
      - 'samples/server/petstore/scala**'
  pull_request:
    paths:
      - 'samples/client/petstore/scala**'
      - 'samples/server/petstore/scala**'
jobs:
  build:
    name: Build Scala client, servers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/client/petstore/scala-akka</module>
          - samples/client/petstore/scala-sttp</module>
          - samples/client/petstore/scala-httpclient</module>
          - samples/client/petstore/scalaz</module>
          # servers
          - samples/server/petstore/scala-lagom-server</module>
          - samples/server/petstore/scala-play-server</module>
          - samples/server/petstore/scala-akka-http-server</module>
          - samples/server/petstore/scalatra</module>
          - samples/server/petstore/scala-finch</module>
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache maven dependencies
        uses: actions/cache@v2.1.7
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.ivy2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/build.sbt') }}
      - name: Build and test
        working-directory: ${{ matrix.sample }}
        run: sbt -v +test
