name: Samples cpp qt client

on:
  push:
    branches:
      - "samples/client/petstore/cpp-qt*/**"
  pull_request:
    paths:
      - "samples/client/petstore/cpp-qt*/**"

env:
  GRADLE_VERSION: 6.9

jobs:
  build:
    name: Build cpp qt client
    strategy:
      matrix:
        sample:
          - samples/client/petstore/cpp-qt
          - samples/client/petstore/cpp-qt-addDownloadProgress
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.7.1"
          target: "desktop"
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: cmake . && cmake --build . --verbose
