name: Samples c libcurl client

on:
  push:
    paths:
      - 'samples/client/petstore/c/**'
      - 'samples/client/petstore/c-useJsonUnformatted/**'
      - 'samples/client/others/c/bearerAuth/**'
  pull_request:
    paths:
      - 'samples/client/petstore/c/**'
      - 'samples/client/petstore/c-useJsonUnformatted/**'
      - 'samples/client/others/c/bearerAuth/**'

jobs:
  build:
    name: Build c libcurl client
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - 'samples/client/petstore/c/'
          - 'samples/client/petstore/c-useJsonUnformatted/'
          - 'samples/client/others/c/bearerAuth/'

    steps:
      - uses: actions/checkout@v5
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: |
          mkdir build
          cd build
          cmake ..
          make
