name: Samples C# .Net Framework Clients

on:
  push:
    paths:
      - samples/client/petstore/csharp/generichost/net4.7/**
      - samples/client/petstore/csharp/generichost/net4.8/**
  pull_request:
    paths:
      - samples/client/petstore/csharp/generichost/net4.7/**
      - samples/client/petstore/csharp/generichost/net4.8/**
jobs:
  build:
    name: Build .Net projects
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/csharp/generichost/net4.7/AllOf
          - samples/client/petstore/csharp/generichost/net4.7/AnyOf
          - samples/client/petstore/csharp/generichost/net4.7/AnyOfNoCompare
          - samples/client/petstore/csharp/generichost/net4.7/FormModels
          - samples/client/petstore/csharp/generichost/net4.7/OneOf
          - samples/client/petstore/csharp/generichost/net4.7/Petstore
          - samples/client/petstore/csharp/generichost/net4.7/UseDateTimeForDate

          - samples/client/petstore/csharp/generichost/net4.8/AllOf
          - samples/client/petstore/csharp/generichost/net4.8/AnyOf
          - samples/client/petstore/csharp/generichost/net4.8/AnyOfNoCompare
          - samples/client/petstore/csharp/generichost/net4.8/FormModels
          - samples/client/petstore/csharp/generichost/net4.8/OneOf
          - samples/client/petstore/csharp/generichost/net4.8/Petstore
          - samples/client/petstore/csharp/generichost/net4.8/UseDateTimeForDate
    steps:
      - uses: actions/checkout@v5
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: dotnet build Org.OpenAPITools.sln
      - name: Test
        working-directory: ${{ matrix.sample }}
        run: dotnet test Org.OpenAPITools.sln
