name: Samples Java Server

on:
  push:
    paths:
      - 'samples/server/petstore/java-vertx-web/**'
      - 'samples/server/petstore/java-inflector/**'
      - 'samples/server/petstore/java-pkmst/**'
      # test in circleci instead
      - 'samples/server/petstore/java-undertow/**'
      - 'samples/server/petstore/java-microprofile/**'
  pull_request:
    paths:
      - 'samples/server/petstore/java-vertx-web/**'
      - 'samples/server/petstore/java-inflector/**'
      - 'samples/server/petstore/java-pkmst/**'
      #- 'samples/server/petstore/java-undertow/**'
      - 'samples/server/petstore/java-microprofile/**'
jobs:
  build:
    name: Build Java Server
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # servers
          - samples/server/petstore/java-vertx-web/
          - samples/server/petstore/java-inflector/
          - samples/server/petstore/java-pkmst/
          #- samples/server/petstore/java-undertow/
          - samples/server/petstore/java-microprofile/
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: mvn clean package --no-transfer-progress
