name: TypeScript Node Client (Encoding / Decoding Test)

on:
  pull_request:
    paths:
      - samples/client/others/typescript-node/encode-decode/**
      - .github/workflows/samples-typescript-node-encode-decode.yaml
jobs:
  build:
    name: Test TypeScript Node Encoding / Decoding
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/client/others/typescript-node/encode-decode/test
        node-version:
          - 16
          - 18
          - 20
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        working-directory: ${{ matrix.sample }}
        run: |
          npm run preinstall
          npm i

      - name: Test
        working-directory: ${{ matrix.sample }}
        run: npm test
