name: Samples JAX-RS (JDK11)

on:
  push:
    paths:
      - samples/server/petstore/jaxrs/jersey3/**
  pull_request:
    paths:
      - samples/server/petstore/jaxrs/jersey3/**
jobs:
  build:
    name: Build JAX-RS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # servers
          - samples/server/petstore/jaxrs/jersey3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: mvn clean package --no-transfer-progress
