name: TypeScript Axios Client (Echo API)

on:
  pull_request:
    paths:
      - samples/client/echo_api/typescript-axios/**
      - .github/workflows/samples-typescript-axios-echo-api.yaml
jobs:
  build:
    name: Test TypeScript Axios client
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/client/echo_api/typescript-axios/test
        node-version:
          - 16
          - 18
          - 20
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run echo server
        run: |
          git clone https://github.com/wing328/http-echo-server -b openapi-generator-test-server
          (cd http-echo-server && git checkout 15a684c41d4de692878636f47fcc1670af309a0f && npm install && npm start &)

      - name: Install
        working-directory: ${{ matrix.sample }}
        run: |
          npm run preinstall
          npm i

      - name: Test
        working-directory: ${{ matrix.sample }}
        run: npm test
