name: Java Client (Echo API) JDK11

on:
  push:
    paths:
      - samples/client/echo_api/java/**
  pull_request:
    paths:
      - samples/client/echo_api/java/**
jobs:
  build:
    name: Build Java Client JDK11
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/client/echo_api/java/apache-httpclient
          - samples/client/echo_api/java/native
          - samples/client/echo_api/java/feign-gson
          - samples/client/echo_api/java/resttemplate
          - samples/client/echo_api/java/resteasy
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Setup node.js
        uses: actions/setup-node@v5
      - name: Run echo server
        run: |
          git clone https://github.com/wing328/http-echo-server -b openapi-generator-test-server
          (cd http-echo-server && npm install && npm start &)
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: mvn clean package --no-transfer-progress
