name: Go Client (Echo API)

on:
  pull_request:
    paths:
      - samples/client/echo_api/go/**
      - .github/workflows/samples-go-client-echo-api.yaml
jobs:
  build:
    name: Test Go client
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/client/echo_api/go
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "stable"
      - name: Setup node.js
        uses: actions/setup-node@v5
      - name: Run echo server
        run: |
          git clone https://github.com/wing328/http-echo-server -b openapi-generator-test-server
          (cd http-echo-server && npm install && npm start &)
      - run: go version
      - name: Run test
        working-directory: ${{ matrix.sample }}
        run: go test -mod=mod -v
