name: Samples Java Spring (JDK17)

on:
  push:
    paths:
      - samples/openapi3/client/petstore/spring-cloud-3-with-optional
      - samples/openapi3/server/petstore/springboot-3
      - samples/server/petstore/springboot-api-response-examples
      - samples/server/petstore/springboot-lombok-data
      - samples/server/petstore/springboot-lombok-tostring
      - samples/server/petstore/springboot-file-delegate-optional
      - samples/server/petstore/springboot-petstore-with-api-response-examples
      - samples/server/petstore/spring-boot-oneof-sealed
      - samples/openapi3/server/petstore/spring-boot-oneof-interface
  pull_request:
    paths:
      - samples/openapi3/client/petstore/spring-cloud-3-with-optional
      - samples/openapi3/server/petstore/springboot-3
      - samples/server/petstore/springboot-api-response-examples
      - samples/server/petstore/springboot-lombok-data
      - samples/server/petstore/springboot-lombok-tostring
      - samples/server/petstore/springboot-file-delegate-optional
      - samples/server/petstore/springboot-petstore-with-api-response-examples
      - samples/server/petstore/spring-boot-oneof-sealed
      - samples/openapi3/server/petstore/spring-boot-oneof-interface
jobs:
  build:
    name: Build Java Spring (JDK17)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/openapi3/client/petstore/spring-cloud-3-with-optional
          # servers
          - samples/openapi3/server/petstore/springboot-3
          - samples/server/petstore/springboot-api-response-examples
          - samples/server/petstore/springboot-lombok-data
          - samples/server/petstore/springboot-lombok-tostring
          - samples/server/petstore/springboot-file-delegate-optional
          - samples/server/petstore/springboot-petstore-with-api-response-examples
          - samples/server/petstore/spring-boot-oneof-sealed
          - samples/openapi3/server/petstore/spring-boot-oneof-interface
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: mvn clean package --no-transfer-progress
