name: Samples PHP 8.x

on:
  push:
    paths:
      - samples/server/petstore/php-symfony/SymfonyBundle-php/**
  pull_request:
    paths:
      - samples/server/petstore/php-symfony/SymfonyBundle-php/**
jobs:
  build:
    name: Build PHP projects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # servers
          - samples/server/petstore/php-symfony/SymfonyBundle-php/
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer, phpunit
      - name: composer install
        working-directory: ${{ matrix.sample }}
        run: composer install
      - name: phpunit
        working-directory: ${{ matrix.sample }}
        run: vendor/bin/phpunit
