name: Samples JDK17
on:
  push:
    paths:
      # clients
      - samples/openapi3/client/petstore/spring-cloud-3/**
      - samples/client/petstore/java-helidon-client/v3/mp/**
      - samples/client/petstore/java-helidon-client/v3/se/**
      - samples/client/petstore/spring-http-interface-reactive/**
      - samples/client/petstore/spring-http-interface/**
      - samples/client/petstore/spring-http-interface-reactive-noResponseEntity/**
      - samples/client/petstore/spring-http-interface-noResponseEntity/**
      - samples/client/petstore/java/webclient-jakarta/**
      - samples/client/petstore/java/microprofile-rest-client-outer-enum/**
      # servers
      - samples/openapi3/server/petstore/springboot-3/**
      - samples/server/petstore/java-camel/**
      - samples/server/petstore/java-helidon-server/v3/mp/**
      - samples/server/petstore/java-helidon-server/v3/se/**
  pull_request:
    paths:
      # clients
      - samples/openapi3/client/petstore/spring-cloud-3/**
      - samples/client/petstore/java-helidon-client/v3/mp/**
      - samples/client/petstore/java-helidon-client/v3/se/**
      - samples/client/petstore/spring-http-interface-reactive/**
      - samples/client/petstore/spring-http-interface/**
      - samples/client/petstore/spring-http-interface-reactive-noResponseEntity/**
      - samples/client/petstore/spring-http-interface-noResponseEntity/**
      - samples/client/petstore/java/webclient-jakarta/**
      - samples/client/petstore/java/microprofile-rest-client-outer-enum/**
      # servers
      - samples/openapi3/server/petstore/springboot-3/**
      - samples/server/petstore/java-camel/**
      - samples/server/petstore/java-helidon-server/v3/mp/**
      - samples/server/petstore/java-helidon-server/v3/se/**
jobs:
  build:
    name: Build with JDK17
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/openapi3/client/petstore/spring-cloud-3
          - samples/client/petstore/java-helidon-client/v3/mp/
          - samples/client/petstore/java-helidon-client/v3/se
          - samples/client/petstore/spring-http-interface-reactive
          - samples/client/petstore/spring-http-interface
          - samples/client/petstore/spring-http-interface-reactive-noResponseEntity
          - samples/client/petstore/spring-http-interface-noResponseEntity
          - samples/client/petstore/java/webclient-jakarta
          - samples/client/petstore/java/microprofile-rest-client-outer-enum
          # servers
          - samples/openapi3/server/petstore/springboot-3
          - samples/server/petstore/java-camel/
          - samples/server/petstore/java-helidon-server/v3/mp/
          - samples/server/petstore/java-helidon-server/v3/se
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: mvn clean package --no-transfer-progress
