name: Samples Kotlin server (jdk21)

on:
  push:
    paths:
      - 'samples/server/others/kotlin-server/**'
      - 'samples/server/petstore/kotlin-server/**'
      - 'samples/server/petstore/kotlin-server-required-and-nullable-properties/**'
  pull_request:
    paths:
      - 'samples/server/others/kotlin-server/**'
      - 'samples/server/petstore/kotlin-server/**'
      - 'samples/server/petstore/kotlin-server-required-and-nullable-properties/**'

env:
  GRADLE_VERSION: '8.10'

jobs:
  build:
    name: Build Kotlin server (jdk21)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/server/others/kotlin-server/polymorphism-allof-and-discriminator
          - samples/server/others/kotlin-server/polymorphism-and-discriminator-disabled-jackson-fix
          - samples/server/others/kotlin-server/polymorphism-and-discriminator
          - samples/server/others/kotlin-server/polymorphism
          - samples/server/petstore/kotlin-server/javalin-6
          - samples/server/petstore/kotlin-server/ktor
          - samples/server/petstore/kotlin-server/ktor2
          - samples/server/petstore/kotlin-server-required-and-nullable-properties
          - samples/server/petstore/kotlin-misk
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Cache maven dependencies
        uses: actions/cache@v5
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Install Gradle wrapper
        uses: eskatos/gradle-command-action@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          build-root-directory: ${{ matrix.sample }}
          arguments: wrapper
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: ./gradlew build -x test
