name: Samples C# .Net 8 Server

on:
  push:
    paths:
      - samples/server/petstore/aspnetcore-8.0/**
      - samples/server/petstore/aspnetcore-8.0-*/**
  pull_request:
    paths:
      - samples/server/petstore/aspnetcore-8.0/**
      - samples/server/petstore/aspnetcore-8.0-*/**
jobs:
  build:
    name: Build .Net 8 servers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/server/petstore/aspnetcore-8.0
          - samples/server/petstore/aspnetcore-8.0-NewtonsoftFalse
          - samples/server/petstore/aspnetcore-8.0-nullableReferenceTypes
          - samples/server/petstore/aspnetcore-8.0-pocoModels
          - samples/server/petstore/aspnetcore-8.0-project4Models
          - samples/server/petstore/aspnetcore-8.0-useSwashBuckle
          - samples/server/petstore/aspnetcore-8.0-use-centralized-package-version-management
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '8.0.x'
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: dotnet build Org.OpenAPITools.sln
      - name: Test
        working-directory: ${{ matrix.sample }}
        run: dotnet test Org.OpenAPITools.sln
