name: Samples Java Helidon

on:
  push:
    paths:
      - samples/client/petstore/java-helidon-client/**
      - samples/server/petstore/java-helidon-server/**
  pull_request:
    paths:
      - samples/client/petstore/java-helidon-client/**
      - samples/server/petstore/java-helidon-server/**
jobs:
  build:
    name: Build Java Helidon 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/java-helidon-client/mp
          - samples/client/petstore/java-helidon-client/se
          - samples/server/petstore/java-helidon-server/mp
          - samples/server/petstore/java-helidon-server/se
        version: [17]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: Cache maven dependencies
        uses: actions/cache@v3
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: mvn clean package
