name: Samples Kotlin server (jdk8)

on:
  push:
    paths:
      - samples/server/others/kotlin-server/jaxrs-spec/**
      - 'samples/server/petstore/kotlin*/**'
      - 'samples/server/others/kotlin-server/jaxrs-spec-array-response/**'
      # comment out due to gradle build failure
      #- samples/server/petstore/kotlin-spring-default/**
  pull_request:
    paths:
      - samples/server/others/kotlin-server/jaxrs-spec/**
      - 'samples/server/petstore/kotlin*/**'
      - 'samples/server/others/kotlin-server/jaxrs-spec-array-response/**'
      # comment out due to gradle build failure
      # - samples/server/petstore/kotlin-spring-default/**

env:
  GRADLE_VERSION: 7.6.4

jobs:
  build:
    name: Build Kotlin server (jdk8)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # server
          - samples/server/petstore/kotlin-springboot
          - samples/server/petstore/kotlin-springboot-multipart-request-model
          - samples/server/petstore/kotlin-springboot-bigdecimal-default
          - samples/server/petstore/kotlin-springboot-delegate
          - samples/server/petstore/kotlin-springboot-modelMutable
          - samples/server/petstore/kotlin-springboot-reactive
          - samples/server/petstore/kotlin-springboot-reactive-without-flow
          - samples/server/petstore/kotlin-springboot-source-swagger1
          - samples/server/petstore/kotlin-springboot-source-swagger2
          - samples/server/petstore/kotlin-springboot-springfox
          - samples/server/petstore/kotlin-springboot-x-kotlin-implements
          - samples/server/petstore/kotlin-server/ktor
          - samples/server/petstore/kotlin-server/ktor2
          - samples/server/petstore/kotlin-server/jaxrs-spec
          - samples/server/petstore/kotlin-server/jaxrs-spec-mutiny
          - samples/server/petstore/kotlin-server-modelMutable
          - samples/server/petstore/kotlin-server/javalin
          - samples/server/others/kotlin-server/jaxrs-spec
          - samples/server/others/kotlin-server/jaxrs-spec-array-response
          - samples/server/petstore/kotlin-spring-cloud
          - samples/server/petstore/kotlin-misk
          - samples/server/petstore/kotlin-misk-config
          # comment out due to gradle build failure
          #- samples/server/petstore/kotlin-spring-default
          # no build.gradle file
          #- samples/server/petstore/kotlin-vertx-modelMutable
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Install Gradle wrapper
        uses: eskatos/gradle-command-action@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          build-root-directory: ${{ matrix.sample }}
          arguments: wrapper
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: ./gradlew build -x test
