name: Samples PHP 8.x

on:
  push:
    paths:
      - samples/server/petstore/php-symfony/SymfonyBundle-php/**
      - samples/server/petstore/php-flight/**
      - samples/server/petstore/php-laravel/**
      - samples/server/petstore/php-laravel-issue-21334/**
  pull_request:
    paths:
      - samples/server/petstore/php-symfony/SymfonyBundle-php/**
      - samples/server/petstore/php-flight/**
      - samples/server/petstore/php-laravel/**
      - samples/server/petstore/php-laravel-issue-21334/**
jobs:
  build:
    name: Build PHP projects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        sample:
          # servers
          - samples/server/petstore/php-symfony/SymfonyBundle-php/
          - samples/server/petstore/php-flight/
          - samples/server/petstore/php-laravel/
          - samples/server/petstore/php-laravel-issue-21334/
    steps:
      - uses: actions/checkout@v5
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: php-cs-fixer, phpunit
      - name: composer install
        working-directory: ${{ matrix.sample }}
        run: composer install
      - name: phpunit
        working-directory: ${{ matrix.sample }}
        run: vendor/bin/phpunit
