name: Samples Kotlin server

on:
  push:
    branches:
      - samples/server/others/kotlin-server/jaxrs-spec/**
      - 'samples/server/petstore/kotlin*/**'
      # comment out due to gradle build failure
      #- samples/server/petstore/kotlin-spring-default/**
  pull_request:
    paths:
      - samples/server/others/kotlin-server/jaxrs-spec/**
      - 'samples/server/petstore/kotlin*/**'
      # comment out due to gradle build failure
      # - samples/server/petstore/kotlin-spring-default/**

env:
  GRADLE_VERSION: 6.9

jobs:
  build:
    name: Build Kotlin server
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # server
          - samples/server/petstore/kotlin-springboot
          - samples/server/petstore/kotlin-springboot-delegate
          - samples/server/petstore/kotlin-springboot-modelMutable
          - samples/server/petstore/kotlin-springboot-reactive
          - samples/server/petstore/kotlin-springboot-source-swagger1
          - samples/server/petstore/kotlin-springboot-source-swagger2
          - samples/server/petstore/kotlin-springboot-springfox
          - samples/server/petstore/kotlin-server/ktor
          - samples/server/petstore/kotlin-server/jaxrs-spec
          - samples/server/petstore/kotlin-server/jaxrs-spec-mutiny
          - samples/server/petstore/kotlin-server-modelMutable
          - samples/server/others/kotlin-server/jaxrs-spec
          # comment out due to gradle build failure
          #- samples/server/petstore/kotlin-spring-default
          # no build.gradle file
          #- samples/server/petstore/kotlin-vertx-modelMutable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Cache maven dependencies
        uses: actions/cache@v3
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Install Gradle wrapper
        uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          build-root-directory: ${{ matrix.sample }}
          arguments: wrapper
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: ./gradlew build -x test
