name: Samples C# .Net 8 Client

on:
  push:
    paths:
      - samples/client/petstore/csharp/restsharp/net8/**
  pull_request:
    paths:
      - samples/client/petstore/csharp/restsharp/net8/**
jobs:
  build:
    name: Build .Net clients
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/csharp/restsharp/net8/ParameterMappings/
          - samples/client/petstore/csharp/restsharp/net8/useVirtualForHooks/
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '8.0.x'
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: dotnet build Org.OpenAPITools.sln
