name: Samples Java Client JDK17

on:
  push:
    paths:
      - samples/client/petstore/java/resttemplate-jakarta/**
      - samples/client/petstore/java/webclient-jakarta/**
  pull_request:
    paths:
      - samples/client/petstore/java/resttemplate-jakarta/**
      - samples/client/petstore/java/webclient-jakarta/**
jobs:
  build:
    name: Build Java Client JDK17
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/client/petstore/java/resttemplate-jakarta
          - samples/client/petstore/java/webclient-jakarta
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache maven dependencies
        uses: actions/cache@v3
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        working-directory: ${{ matrix.sample }}
        run: mvn clean package
      - name: Build with Gradle
        working-directory: ${{ matrix.sample }}
        run: gradle clean build
