name: Samples C# .Net 10 Clients

on:
  push:
    paths:
      - samples/client/petstore/csharp/generichost/latest/**
      - samples/client/petstore/csharp/generichost/net10/**
      - samples/client/petstore/csharp/httpclient/net10/**
      - samples/client/petstore/csharp/restsharp/net10/**
      - samples/client/petstore/csharp/unityWebRequest/net10/**
  pull_request:
    paths:
      - samples/client/petstore/csharp/generichost/latest/**
      - samples/client/petstore/csharp/generichost/net10/**
      - samples/client/petstore/csharp/httpclient/net10/**
      - samples/client/petstore/csharp/restsharp/net10/**
      - samples/client/petstore/csharp/unityWebRequest/net10/**
jobs:
  build:
    name: Build .Net 10 projects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/csharp/generichost/latest/ComposedEnum
          - samples/client/petstore/csharp/generichost/latest/InlineEnumAnyOf
          - samples/client/petstore/csharp/generichost/latest/Tags
          - samples/client/petstore/csharp/generichost/latest/HelloWorld
          - samples/client/petstore/csharp/generichost/latest/OneOfList
          - samples/client/petstore/csharp/generichost/net10/AllOf
          - samples/client/petstore/csharp/generichost/net10/AnyOf
          - samples/client/petstore/csharp/generichost/net10/AnyOfNoCompare
          - samples/client/petstore/csharp/generichost/net10/FormModels
          # - samples/client/petstore/csharp/generichost/net10/ManualPetstoreTests
          # - samples/client/petstore/csharp/generichost/net10/ManualSourceGenerationTests
          - samples/client/petstore/csharp/generichost/net10/NullReferenceTypes
          - samples/client/petstore/csharp/generichost/net10/OneOf
          - samples/client/petstore/csharp/generichost/net10/Petstore
          - samples/client/petstore/csharp/generichost/net10/SourceGeneration
          - samples/client/petstore/csharp/generichost/net10/UseDateTimeForDate
          # restsharp
          - samples/client/petstore/csharp/restsharp/net10/EnumMappings
          # httpclient
          - samples/client/petstore/csharp/httpclient/net10/Petstore
          - samples/client/petstore/csharp/httpclient/net10/Petstore-nonPublicApi
          # unity
          # - samples/client/petstore/csharp/unityWebRequest/net10/Petstore
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '10.x'
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: dotnet build Org.OpenAPITools.sln
      - name: Test
        working-directory: ${{ matrix.sample }}
        run: dotnet test Org.OpenAPITools.sln
