name: "Python Client: Petstore"

on:
  pull_request:
    paths:
      - samples/openapi3/client/petstore/python-aiohttp/**
      - samples/openapi3/client/petstore/python/**
      - .github/workflows/samples-python-petstore.yaml

jobs:
  validate-pyproject-toml:
    name: Validate pyproject.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install validator
        run: pip install 'validate-pyproject[all]'
      - name: Validate
        run: validate-pyproject samples/openapi3/client/petstore/python/pyproject.toml
  build:
    name: Test Python client
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        sample:
          - samples/openapi3/client/petstore/python-aiohttp
          - samples/openapi3/client/petstore/python
          - samples/openapi3/client/petstore/python-lazyImports
    services:
      petstore-api:
        image: swaggerapi/petstore
        ports:
          - 80:8080
        env:
          SWAGGER_HOST: http://petstore.swagger.io
          SWAGGER_BASE_PATH: /v2
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        id: py
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-python-${{ steps.py.outputs.python-version }}-
          path: |
            ~/.cache/pypoetry/virtualenvs/
            ~/.local/pipx/venvs/poetry/
            .mypy_cache/

      - name: Install poetry
        run: pipx install --python '${{ steps.py.outputs.python-path }}' poetry

      - name: Install
        working-directory: ${{ matrix.sample }}
        run: poetry install

      - name: Test
        working-directory: ${{ matrix.sample }}
        run: poetry run pytest -v

      - name: mypy
        working-directory: ${{ matrix.sample }}
        run: poetry run mypy
