name: Samples JDK21
on:
  push:
    paths:
      # clients
      - samples/client/petstore/java-helidon-client/v4/mp/**
      - samples/client/petstore/java-helidon-client/v4/se/**
      # servers
      - samples/server/petstore/java-helidon-server/v4/mp/**
      - samples/server/petstore/java-helidon-server/v4/se/**
  pull_request:
    paths:
      # clients
      - samples/client/petstore/java-helidon-client/v4/mp/**
      - samples/client/petstore/java-helidon-client/v4/se/**
      # servers
      - samples/server/petstore/java-helidon-server/v4/mp/**
      - samples/server/petstore/java-helidon-server/v4/se/**
jobs:
  build:
    name: Build with JDK21
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # clients
          - samples/client/petstore/java-helidon-client/v4/mp/
          - samples/client/petstore/java-helidon-client/v4/se/
          # servers
          - samples/server/petstore/java-helidon-server/v4/mp/
          - samples/server/petstore/java-helidon-server/v4/se/
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: maven-repository
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: mvn clean package --no-transfer-progress
