name: Python Server

on:
  push:
    paths:
      - samples/server/petstore/python-aiohttp-srclayout/**
  pull_request:
    paths:
      - samples/server/petstore/python-aiohttp-srclayout/**
jobs:
  build:
    name: Test Python server
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          # servers
          - samples/server/petstore/python-aiohttp-srclayout/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Test
        working-directory: ${{ matrix.sample }}
        run: make test-all
