name: Samples C# .Net 6 Client

on:
  push:
    paths:
      - samples/client/petstore/csharp/restsharp/net6/**
  pull_request:
    paths:
      - samples/client/petstore/csharp/restsharp/net6/**
jobs:
  build:
    name: Build .Net clients
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/csharp/restsharp/net6/OpenAPIClient-restsharp-name-parameter-mappings/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '6.0.x'
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: dotnet build Org.OpenAPITools.sln
